package mihomo

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestApplySubscriptionMergesCustomBeforeSubscriptionAndGroups(t *testing.T) {
	store := Store{BaseDir: t.TempDir()}
	if err := store.EnsureDirs(); err != nil {
		t.Fatalf("EnsureDirs() error = %v", err)
	}

	writeTestFile(t, store.BaseConfigPath(), "mode: rule\n")
	writeTestFile(t, store.RulesPath(), `rules:
- PROCESS-NAME,custom.exe,Custom
- GEOIP,CN,GEOIP-CN,no-resolve
- MATCH,Final
`)
	writeTestFile(t, store.ProxyGroupsPath(), `proxy-groups:
- -Custom
- +Final
`)
	writeTestFile(t, store.CustomProxiesPath(), `proxies:
- {name: Custom One, server: 127.0.0.1, port: 1080, type: socks5}
`)

	subscriptionFile := "subscription-test.yaml"
	writeTestFile(t, store.ProfilePath(subscriptionFile), `proxies:
  - {name: 未知 SS-01 | free-nodes, server: 62.146.231.112, port: 12012, type: ss, cipher: chacha20-ietf-poly1305, password: secret}
  - name: Block Node
    server: example.com
    port: 443
    type: vmess
`)

	result, err := store.ApplySubscription(ApplyOptions{
		Subscription: Subscription{
			Name: "测试订阅",
			File: subscriptionFile,
			URL:  "https://example.com/sub",
		},
		GenerateProxyGroups: true,
	})
	if err != nil {
		t.Fatalf("ApplySubscription() error = %v", err)
	}

	finalData, err := os.ReadFile(store.FinalConfigPath())
	if err != nil {
		t.Fatalf("ReadFile(final config) error = %v", err)
	}
	final := string(finalData)

	assertContains(t, final, "proxies:\n  - {name: Custom One")
	assertContains(t, final, "  - {name: 未知 SS-01 | free-nodes")
	assertBefore(t, final, "Custom One", "未知 SS-01 | free-nodes")
	assertContains(t, final, "- name: Snail")
	assertContains(t, final, "  - \"Custom One\"")
	assertContains(t, final, "- name: Proxies")
	assertContains(t, final, "  - \"未知 SS-01 | free-nodes\"")
	assertContains(t, final, "- name: Custom")
	assertContains(t, final, "  - DIRECT")
	assertContains(t, final, "- name: Final")
	assertContains(t, final, "rules:\n- PROCESS-NAME,custom.exe,Custom")

	if result.ProxyCount != 2 {
		t.Fatalf("ProxyCount = %d, want 2", result.ProxyCount)
	}
	if result.CustomProxyCount != 1 {
		t.Fatalf("CustomProxyCount = %d, want 1", result.CustomProxyCount)
	}
	if result.GroupCount != 4 {
		t.Fatalf("GroupCount = %d, want 4", result.GroupCount)
	}
	if len(result.Warnings) != 1 || !strings.Contains(result.Warnings[0], "GEOIP-CN") {
		t.Fatalf("Warnings = %#v, want missing GEOIP-CN warning", result.Warnings)
	}
}

func TestExtractTopLevelListBlockAllowsHeaderComments(t *testing.T) {
	lines, err := extractTopLevelListBlock(`proxies: # generated by provider
  - {name: Node}
proxy-groups:
  - name: Proxies
`, "proxies")
	if err != nil {
		t.Fatalf("extractTopLevelListBlock() error = %v", err)
	}
	if len(lines) != 1 || !strings.Contains(lines[0], "Node") {
		t.Fatalf("lines = %#v, want one proxy line", lines)
	}
}

func TestDefaultMihomoConfigGeneratesRandomSecret(t *testing.T) {
	first, err := defaultMihomoConfig()
	if err != nil {
		t.Fatalf("defaultMihomoConfig() error = %v", err)
	}
	second, err := defaultMihomoConfig()
	if err != nil {
		t.Fatalf("defaultMihomoConfig() second error = %v", err)
	}

	secret := configLineValue(t, first, "secret: ")
	if secret == "set-your-secret" {
		t.Fatalf("secret should not use placeholder value")
	}
	if len(secret) != 100 {
		t.Fatalf("secret length = %d, want 100", len(secret))
	}
	if !isAlphaNumeric(secret) {
		t.Fatalf("secret should be alphanumeric, got %q", secret)
	}
	if secret == configLineValue(t, second, "secret: ") {
		t.Fatalf("secret should be regenerated for each default config")
	}
}

func writeTestFile(t *testing.T, targetPath string, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(targetPath), 0o755); err != nil {
		t.Fatalf("MkdirAll(%s) error = %v", filepath.Dir(targetPath), err)
	}
	if err := os.WriteFile(targetPath, []byte(content), 0o644); err != nil {
		t.Fatalf("WriteFile(%s) error = %v", targetPath, err)
	}
}

func configLineValue(t *testing.T, content string, prefix string) string {
	t.Helper()
	for _, line := range strings.Split(content, "\n") {
		if strings.HasPrefix(line, prefix) {
			return strings.TrimSpace(strings.TrimPrefix(line, prefix))
		}
	}
	t.Fatalf("expected config to contain line prefix %q\n%s", prefix, content)
	return ""
}

func isAlphaNumeric(value string) bool {
	for _, r := range value {
		if r >= 'a' && r <= 'z' {
			continue
		}
		if r >= 'A' && r <= 'Z' {
			continue
		}
		if r >= '0' && r <= '9' {
			continue
		}
		return false
	}
	return true
}

func assertContains(t *testing.T, value string, needle string) {
	t.Helper()
	if !strings.Contains(value, needle) {
		t.Fatalf("expected output to contain %q\n%s", needle, value)
	}
}

func assertBefore(t *testing.T, value string, first string, second string) {
	t.Helper()
	firstIndex := strings.Index(value, first)
	secondIndex := strings.Index(value, second)
	if firstIndex < 0 || secondIndex < 0 || firstIndex >= secondIndex {
		t.Fatalf("expected %q to appear before %q\n%s", first, second, value)
	}
}
