package mihomo

import (
	"context"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestApplySubscriptionMergesCustomBeforeSubscriptionAndGroups(t *testing.T) {
	store := Store{BaseDir: t.TempDir()}
	if err := store.EnsureDirs(); err != nil {
		t.Fatalf("EnsureDirs() error = %v", err)
	}

	writeTestFile(t, store.BaseConfigPath(), "mode: rule\n")
	writeTestFile(t, store.RulesPath(), `rules:
- PROCESS-NAME,custom.exe,Custom
- GEOIP,CN,GEOIP-CN,no-resolve
- MATCH,Final
`)
	writeTestFile(t, store.ProxyGroupsPath(), `proxy-groups:
- -Custom
- +Final
`)
	writeTestFile(t, store.CustomProxiesPath(), `proxies:
- {name: Custom One, server: 127.0.0.1, port: 1080, type: socks5}
`)

	subscriptionFile := "subscription-test.yaml"
	writeTestFile(t, store.ProfilePath(subscriptionFile), `proxies:
  - {name: 未知 SS-01 | free-nodes, server: 62.146.231.112, port: 12012, type: ss, cipher: chacha20-ietf-poly1305, password: secret}
  - name: Block Node
    server: example.com
    port: 443
    type: vmess
`)

	result, err := store.ApplySubscription(ApplyOptions{
		Subscription: Subscription{
			Name: "测试订阅",
			File: subscriptionFile,
			URL:  "https://example.com/sub",
		},
		GenerateProxyGroups: true,
	})
	if err != nil {
		t.Fatalf("ApplySubscription() error = %v", err)
	}

	finalData, err := os.ReadFile(store.FinalConfigPath())
	if err != nil {
		t.Fatalf("ReadFile(final config) error = %v", err)
	}
	final := string(finalData)

	assertContains(t, final, "proxies:\n  - {name: Custom One")
	assertContains(t, final, "  - {name: 未知 SS-01 | free-nodes")
	assertBefore(t, final, "Custom One", "未知 SS-01 | free-nodes")
	assertContains(t, final, "- name: Snail")
	assertContains(t, final, "  - \"Custom One\"")
	assertContains(t, final, "- name: Proxies")
	assertContains(t, final, "  - \"未知 SS-01 | free-nodes\"")
	assertContains(t, final, "- name: Custom")
	assertContains(t, final, "  - DIRECT")
	assertContains(t, final, "- name: Final")
	assertContains(t, final, "rules:\n- PROCESS-NAME,custom.exe,Custom")

	if result.ProxyCount != 2 {
		t.Fatalf("ProxyCount = %d, want 2", result.ProxyCount)
	}
	if result.CustomProxyCount != 1 {
		t.Fatalf("CustomProxyCount = %d, want 1", result.CustomProxyCount)
	}
	if result.GroupCount != 4 {
		t.Fatalf("GroupCount = %d, want 4", result.GroupCount)
	}
	if len(result.Warnings) != 1 || !strings.Contains(result.Warnings[0], "GEOIP-CN") {
		t.Fatalf("Warnings = %#v, want missing GEOIP-CN warning", result.Warnings)
	}
}

func TestCopySubscriptionToFinalConfigPreservesContent(t *testing.T) {
	store := Store{BaseDir: t.TempDir()}
	if err := store.EnsureDirs(); err != nil {
		t.Fatalf("EnsureDirs() error = %v", err)
	}

	subscriptionFile := "subscription-test.yaml"
	subscriptionContent := `mixed-port: 7890
proxies:
  - {name: Node A, server: example.com, port: 443, type: ss, cipher: chacha20-ietf-poly1305, password: secret}
proxy-groups:
  - name: Proxies
    type: select
    proxies:
      - Node A
rules:
  - MATCH,Proxies
`
	writeTestFile(t, store.ProfilePath(subscriptionFile), subscriptionContent)

	finalPath, err := store.CopySubscriptionToFinalConfig(Subscription{
		Name: "测试订阅",
		File: subscriptionFile,
		URL:  "https://example.com/sub",
	})
	if err != nil {
		t.Fatalf("CopySubscriptionToFinalConfig() error = %v", err)
	}
	if finalPath != store.FinalConfigPath() {
		t.Fatalf("finalPath = %q, want %q", finalPath, store.FinalConfigPath())
	}
	assertTestFileContent(t, store.FinalConfigPath(), subscriptionContent)
	assertTestFileContent(t, store.ProfilePath(subscriptionFile), subscriptionContent)
}

func TestExtractTopLevelListBlockAllowsHeaderComments(t *testing.T) {
	lines, err := extractTopLevelListBlock(`proxies: # generated by provider
  - {name: Node}
proxy-groups:
  - name: Proxies
`, "proxies")
	if err != nil {
		t.Fatalf("extractTopLevelListBlock() error = %v", err)
	}
	if len(lines) != 1 || !strings.Contains(lines[0], "Node") {
		t.Fatalf("lines = %#v, want one proxy line", lines)
	}
}

func TestDefaultMihomoConfigGeneratesRandomSecret(t *testing.T) {
	first, err := defaultMihomoConfig()
	if err != nil {
		t.Fatalf("defaultMihomoConfig() error = %v", err)
	}
	second, err := defaultMihomoConfig()
	if err != nil {
		t.Fatalf("defaultMihomoConfig() second error = %v", err)
	}

	secret := configLineValue(t, first, "secret: ")
	if secret == "set-your-secret" {
		t.Fatalf("secret should not use placeholder value")
	}
	if len(secret) != 100 {
		t.Fatalf("secret length = %d, want 100", len(secret))
	}
	if !isAlphaNumeric(secret) {
		t.Fatalf("secret should be alphanumeric, got %q", secret)
	}
	if secret == configLineValue(t, second, "secret: ") {
		t.Fatalf("secret should be regenerated for each default config")
	}
}

func TestValidateSubscriptionDataRequiresValidYAMLWithProxies(t *testing.T) {
	tests := []struct {
		name    string
		content string
		wantErr string
	}{
		{
			name: "valid",
			content: `proxies:
  - name: Node A
    type: ss
    server: example.com
    port: 443
`,
		},
		{
			name: "invalid yaml",
			content: `proxies:
  - name: Node A
    port: [`,
			wantErr: "订阅 YAML 无效",
		},
		{
			name: "missing proxies",
			content: `proxy-groups:
  - name: Proxies
`,
			wantErr: "缺少 proxies",
		},
		{
			name: "empty proxies",
			content: `proxies: []
`,
			wantErr: "proxies 不能为空",
		},
		{
			name: "proxy without name",
			content: `proxies:
  - type: ss
    server: example.com
    port: 443
`,
			wantErr: "没有可用 name",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := ValidateSubscriptionData([]byte(tt.content))
			if tt.wantErr == "" {
				if err != nil {
					t.Fatalf("ValidateSubscriptionData() error = %v", err)
				}
				return
			}
			if err == nil || !strings.Contains(err.Error(), tt.wantErr) {
				t.Fatalf("ValidateSubscriptionData() error = %v, want containing %q", err, tt.wantErr)
			}
		})
	}
}

func TestDownloadSubscriptionRejectsInvalidYAMLWithoutReplacingExistingFile(t *testing.T) {
	targetPath := filepath.Join(t.TempDir(), "subscription.yaml")
	if err := os.WriteFile(targetPath, []byte("existing\n"), 0o644); err != nil {
		t.Fatalf("WriteFile(existing) error = %v", err)
	}

	body := "not: [valid"
	client := &http.Client{
		Transport: roundTripFunc(func(req *http.Request) (*http.Response, error) {
			return &http.Response{
				StatusCode:    http.StatusOK,
				Status:        "200 OK",
				Body:          io.NopCloser(strings.NewReader(body)),
				ContentLength: int64(len(body)),
				Header:        make(http.Header),
				Request:       req,
			}, nil
		}),
	}
	req, err := http.NewRequestWithContext(context.Background(), http.MethodGet, "https://example.com/sub", nil)
	if err != nil {
		t.Fatalf("NewRequestWithContext() error = %v", err)
	}

	err = downloadSubscriptionWithClient(client, req, targetPath)
	if err == nil || !strings.Contains(err.Error(), "订阅 YAML 无效") {
		t.Fatalf("downloadSubscriptionWithClient() error = %v, want invalid YAML error", err)
	}

	data, err := os.ReadFile(targetPath)
	if err != nil {
		t.Fatalf("ReadFile(target) error = %v", err)
	}
	if string(data) != "existing\n" {
		t.Fatalf("target file was replaced: %q", data)
	}
	if _, err := os.Stat(targetPath + ".download"); !os.IsNotExist(err) {
		t.Fatalf("temporary download file should be removed, stat err = %v", err)
	}
}

type roundTripFunc func(*http.Request) (*http.Response, error)

func (f roundTripFunc) RoundTrip(req *http.Request) (*http.Response, error) {
	return f(req)
}

func writeTestFile(t *testing.T, targetPath string, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(targetPath), 0o755); err != nil {
		t.Fatalf("MkdirAll(%s) error = %v", filepath.Dir(targetPath), err)
	}
	if err := os.WriteFile(targetPath, []byte(content), 0o644); err != nil {
		t.Fatalf("WriteFile(%s) error = %v", targetPath, err)
	}
}

func assertTestFileContent(t *testing.T, targetPath string, want string) {
	t.Helper()
	data, err := os.ReadFile(targetPath)
	if err != nil {
		t.Fatalf("ReadFile(%s) error = %v", targetPath, err)
	}
	if string(data) != want {
		t.Fatalf("ReadFile(%s) = %q, want %q", targetPath, data, want)
	}
}

func configLineValue(t *testing.T, content string, prefix string) string {
	t.Helper()
	for _, line := range strings.Split(content, "\n") {
		if strings.HasPrefix(line, prefix) {
			return strings.TrimSpace(strings.TrimPrefix(line, prefix))
		}
	}
	t.Fatalf("expected config to contain line prefix %q\n%s", prefix, content)
	return ""
}

func isAlphaNumeric(value string) bool {
	for _, r := range value {
		if r >= 'a' && r <= 'z' {
			continue
		}
		if r >= 'A' && r <= 'Z' {
			continue
		}
		if r >= '0' && r <= '9' {
			continue
		}
		return false
	}
	return true
}

func assertContains(t *testing.T, value string, needle string) {
	t.Helper()
	if !strings.Contains(value, needle) {
		t.Fatalf("expected output to contain %q\n%s", needle, value)
	}
}

func assertBefore(t *testing.T, value string, first string, second string) {
	t.Helper()
	firstIndex := strings.Index(value, first)
	secondIndex := strings.Index(value, second)
	if firstIndex < 0 || secondIndex < 0 || firstIndex >= secondIndex {
		t.Fatalf("expected %q to appear before %q\n%s", first, second, value)
	}
}
